apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: keda
spec:
  destination:
    name: 'in-cluster'
    namespace: keda
  source:
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 2.8.2
    helm:
      valueFiles:
        - values.yaml
      values: |-
        prometheus:
          metricServer:
            enabled: true
            port: 9022
            portName: http-metrics
            path: /metrics
    chart: keda
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
          - /spec/replicas