apiVersion: v1
kind: Secret
metadata:
  name: repo-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  type: Z2l0
  url: >-
    aHR0cHM6Ly9naXRodWIuY29tL1l1Q2hpYS1XZWkvYXJnby1wcm9qLWt1c3RvbWl6YXRpb24td2l0aC1pc3Rpbw==
