apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: argocd-core
  namespace: argocd
  name: cluster-infra-production
spec:
  destination:
    name: 'in-cluster'
    namespace: argocd
  source:
    path: deploy/kustomization/argocd-application/cluster-infra/env-production
    repoURL: >-
      https://github.com/YuChia-Wei/argoproj-deploy
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
