apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-elastic-system-apps
spec:
  generators:
  - list:
      elements:
      - env: inner-cluster
      # - env: production
      # - env: stage
      # - env: test
  template:
    metadata:
      labels:
        type: argocd-core
      namespace: argocd
      name: 'apps-elastic-system-{{env}}'
    spec:
      destination:
        name: 'in-cluster'
        namespace: argocd
      source:
        path: 'deploy/kustomization/argocd-application/elastic-system/env-{{env}}'
        repoURL: >-
          https://github.com/YuChia-Wei/argoproj-deploy
        targetRevision: main
      project: default