apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-applicationset-controller
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: argocd
    version: v3.0.12
  name: argocd-applicationset-controller
spec:
  template:
    metadata:
      labels:
        app: argocd-applicationset-controller
        version: v3.0.12
