apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-dex-server
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
    version: v2.37.0
  name: argocd-dex-server
spec:
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: argocd-dex-server
        version: v2.37.0
