apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9001'
    prometheus.io/scrape: 'true'
  name: argocd-notifications-controller-metrics
spec:
  ports:
  - name: http-metrics
    port: 9001
    protocol: TCP
    targetPort: 9001
