apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../base
- core-app/
- install-ha.yaml
  # or use this (ref https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize)
  # - https://raw.githubusercontent.com/argoproj/argo-cd/v{version}/manifests/ha/install.yaml
patches:
- path: patches_configmap.yaml
- path: istio-patches/deployment_argocd-applicationset-controller.yaml
- path: istio-patches/deployment_argocd-dex-server.yaml
- path: istio-patches/deployment_argocd-notifications-controller.yaml
- path: istio-patches/deployment_argocd-redis-ha-haproxy.yaml
- path: istio-patches/deployment_argocd-repo-server.yaml
- path: istio-patches/deployment_argocd-server.yaml
- path: istio-patches/service_argocd-applicationset-controller.yaml
- path: istio-patches/service_argocd-dex-server.yaml
- path: istio-patches/service_argocd-metrics.yaml
- path: istio-patches/service_argocd-notifications-controller-metrics.yaml
- path: istio-patches/service_argocd-repo-server.yaml
- path: istio-patches/service_argocd-server-metrics.yaml
- path: istio-patches/service_argocd-server.yaml
- path: istio-patches/statefulset_argocd-application-controller.yaml
- path: istio-patches/statefulset_argocd-redis-ha-server.yaml
