apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - core-app/
  - ../argocd-system-settings
  - ../internal-cluster-settings
  - install-ha.yaml
  # or use this (ref https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize)
  # - github.com/argoproj/argo-cd/manifests/ha?ref=v2.6.2
patchesStrategicMerge:
  - istio_patches_service.yaml
  - istio_patches_deployment.yaml
  - istio_patches_statefulset.yaml
  - patches_configmap.yaml