apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: prometheus-adapter
spec:
  destination:
    name: 'in-cluster'
    namespace: observability
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 3.3.1
    chart: prometheus-adapter
    helm:
      releaseName: prometheus-adapter
      valueFiles:
        - values.yaml
      values: |-
        rules:
          default: true
          resource:
            cpu:
              containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, container!=""}[3m])) by (<<.GroupBy>>)
              nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[3m])) by (<<.GroupBy>>)
              resources:
                overrides:
                  node:
                    resource: node
                  namespace:
                    resource: namespace
                  pod:
                    resource: pod
              containerLabel: container
            memory:
              containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>, container!=""}) by (<<.GroupBy>>)
              nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
              resources:
                overrides:
                  node:
                    resource: node
                  namespace:
                    resource: namespace
                  pod:
                    resource: pod
              containerLabel: container
            window: 3m
          custom:
          - seriesQuery: '{__name__=~"istio_requests_total"}'
            seriesFilters: []
            resources:
              overrides:
                kubernetes_namespace:
                  resource: namespace
                kubernetes_pod_name:
                  resource: pod
                destination_service_name:
                  resource: service
            name:
              matches: "^(.*)_total"
              as: "${1}_per_min"
            metricsQuery: sum(increase(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
      parameters:
        - name: prometheus.url
          value: 'http://prometheus-server.observability.svc.cluster.local'
        - name: prometheus.port
          value: '80'
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 3