apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - appset-argo-rollouts-apps.yaml
  - appset-cache-apps.yaml
  - appset-keda-apps.yaml
  - appset-observability-apps.yaml