apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../base
patches:
- path: env-patch.yaml
  target:
    kind: Application
- path: resource-patches/elastic-agent.yaml
- path: resource-patches/elasticsearch.yaml
- path: resource-patches/fleet-server.yaml
- path: resource-patches/kibana.yaml
nameSuffix: -production
