apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - core-app/
  - ../argocd-system-settings
  - ../internal-cluster-settings
  - install.yaml
patchesStrategicMerge:
  - istio_patches_service.yaml
  - istio_patches_deployment.yaml
  - istio_patches_statefulset.yaml
  - patches_configmap.yaml