apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: argocd-core
  namespace: argocd
  name: argocd-core
spec:
  destination:
    name: 'in-cluster'
    namespace: argocd
  source:
    path: ArgoCD/ver-2.4.13
    repoURL: >-
      https://github.com/YuChia-Wei/argo-proj-kustomization-with-istio
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
