apiVersion: v1
kind: Secret
metadata:
  name: repo-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  password: --
  project: ZGVmYXVsdA==
  type: Z2l0
  url: >-
    --
  username: --
