apiVersion: v1
kind: Secret
metadata:
  name: repo-grafana-helm-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: grafana
  url: https://grafana.github.io/helm-charts
  type: helm
  project: default