apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: argo-rollouts
spec:
  destination:
    name: 'in-cluster'
    namespace: argo-rollouts
  source:
    path: Argo-Rollouts
    repoURL: >-
      https://github.com/YuChia-Wei/argo-proj-kustomization-with-istio
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true