#this is memo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: webapi
  namespace: argocd
  name: dotnet-webapi-lab
spec:
  destination:
    name: 'in-cluster'
    namespace: lab
  source:
    path: deploy/helm-chart/dotnet-webapi
    repoURL: 'https://github.com/YuChia-Wei/dotnet-webapi-lab'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 3