apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: cert-manager
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
    server: ''
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.9.1
    chart: cert-manager
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 3