apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../base
patchesStrategicMerge:
- path-patch.yaml
patches:
- path: env-patch.yaml
  target:
    kind: Application
nameSuffix: -stage