apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
  namespace: argocd
spec:
  description: 測試環境
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: Test
      namespace: '*'
      server: https://rancher.local.vm/k8s/clusters/{cluster-id}
  sourceRepos:
    - '*'