apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
    app: argo-rollouts
    version: v1.4.0
  name: argo-rollouts
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8090"
      labels:
        app: argo-rollouts
        version: v1.4.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: argo-rollouts-dashboard
    app.kubernetes.io/name: argo-rollouts-dashboard
    app.kubernetes.io/part-of: argo-rollouts
    app: argo-rollouts-dashboard
    version: v1.4.0
  name: argo-rollouts-dashboard
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-rollouts-dashboard
        app: argo-rollouts-dashboard
        version: v1.4.0