apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts
resources:
- argo-rollouts-namespace.yaml
- install.yaml
- dashboard-install.yaml
patches:
- path: istio-patches/deployment_argo-rollouts-dashboard.yaml
- path: istio-patches/deployment_argo-rollouts.yaml
- path: istio-patches/service_argo-rollouts-metrics.yaml