apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts
resources:
  - install.yaml
  - dashboard-install.yaml
patchesStrategicMerge:
  - istio_patches_service.yaml
  - istio_patches_deployment.yaml