apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts
resources:
- argo-rollouts-namespace.yaml
- install.yaml
- dashboard-install.yaml
patches:
- path: istio_patches_service.yaml
- path: istio_patches_deployment.yaml
