apiVersion: v1
kind: Secret
metadata:
  name: repo-prometheus-community-helm-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
  type: helm
  project: default