apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: loki
spec:
  destination:
    name: 'in-cluster'
    namespace: kube-monitor
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.16.0
    chart: loki
    helm:
      releaseName: loki
      valueFiles:
        - values.yaml
      values: |-
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "http-metrics"
          prometheus.io/path: "/metrics"
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 3