apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: minio
spec:
  destination:
    name: 'in-cluster'
    namespace: kube-monitor
  source:
    repoURL: 'https://charts.min.io/'
    targetRevision: 5.0.1
    chart: minio
    helm:
      parameters:
        - name: persistence.size
          value: 5Gi
        - name: resources.requests.memory
          value: 256Mi
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 3