apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: service-logging-grafana
spec:
  destination:
    name: 'in-cluster'
    namespace: kube-monitor
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.45.0
    chart: grafana
    helm:
      releaseName: service-logging-grafana
      valueFiles:
        - values.yaml
      values: |-
        datasources: 
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              isDefault: true
              uid: loki
              url: http://loki.kube-monitor.svc.cluster.local:3100
              access: proxy
              orgId: 1
              editable: false
              jsonData:
                timeInterval: 5s
            - name: Tempo
              type: tempo
              isDefault: false
              uid: tempo
              url: http://tempo-query-frontend.kube-monitor.svc.cluster.local:3100
              access: proxy
              orgId: 1
              editable: false
              basicAuth: false
              version: 1
              apiVersion: 1
      parameters:
        - name: env.GF_AUTH_ANONYMOUS_ENABLED
          value: 'true'
        - name: env.GF_AUTH_ANONYMOUS_ORG_ROLE
          value: 'Admin'
        - name: env.GF_AUTH_DISABLE_LOGIN_FORM
          value: 'true'
        - name: env.GF_FEATURE_TOGGLES_ENABLE
          value: 'tempoSearch tempoBackendSearch'
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 3