apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: tempo
spec:
  destination:
    name: 'in-cluster'
    namespace: kube-monitor
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 0.27.10
    chart: tempo-distributed
    helm:
      releaseName: tempo
      valueFiles:
        - values.yaml
      parameters:
        - name: search.enabled
          value: 'true'
        - name: global.dnsService
          value: rke2-coredns-rke2-coredns
        - name: traces.otlp.grpc.enabled
          value: 'true'
        - name: traces.otlp.http.enabled
          value: 'true'
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 3