apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-redis-ha-haproxy
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: argocd-redis-ha-haproxy
    app.kubernetes.io/part-of: argocd
    version: 2.6.14-alpine
  name: argocd-redis-ha-haproxy
spec:
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: argocd-redis-ha-haproxy
        version: 2.6.14-alpine
