apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-redis-ha-haproxy
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: argocd-redis-ha-haproxy
    app.kubernetes.io/part-of: argocd
    # 這邊的版本改與 argocd 官方 helm 慣用規則相同，統一使用 argocd 的版本號
    version: v3.0.12
    # haproxy version
    # version: 3.0.8-alpine
  name: argocd-redis-ha-haproxy
spec:
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: argocd-redis-ha-haproxy
        # 這邊的版本改與 argocd 官方 helm 慣用規則相同，統一使用 argocd 的版本號
        version: v3.0.12
        # haproxy version
        # version: 3.0.8-alpine
