apiVersion: v1
kind: Service
metadata:
  name: argocd-applicationset-controller
spec:
  ports:
  - name: http-webhook
    port: 7000
    protocol: TCP
    targetPort: webhook
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
