apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: argocd-redis-ha-server
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: argocd-redis-ha
    app.kubernetes.io/part-of: argocd
    # 這邊的版本改與 argocd 官方 helm 慣用規則相同，統一使用 argocd 的版本號
    version: v3.0.12
    # redis version
    # version: v7.2.7-alpine
  name: argocd-redis-ha-server
spec:
  template:
    metadata:
      labels:
        app: argocd-redis-ha
        # 這邊的版本改與 argocd 官方 helm 慣用規則相同，統一使用 argocd 的版本號
        version: v3.0.12
        # redis version
        # version: v7.2.7-alpine

