apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  name: fleet-server
  namespace: argocd
spec:
  source:
    path: elastic-system/fleet-server/env-stage
